title: Margaret Liu Data Science Projects
#logo 
description: A personal site for data science projects and more. 
# show_downloads: true # Uncomment if your theme supports it 
theme: jekyll-theme-minimal
